CREATE DATABASE DB_PORTALCRUD;

USE DB_PORTALCRUD;

CREATE TABLE `TBL_ACCOUNT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STUDENT_NUMBER` varchar(50) NOT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `MIDDLE_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `SUFFIX_NAME` varchar(50) NOT NULL,
  `COURSE` varchar(50) NOT NULL,
  `CAMPUS` varchar(50) NOT NULL,
  `CONTACT_NUMBER` varchar(50) NOT NULL,
  `EMAIL_ADDRESS` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `USER_ROLE` varchar(50) NOT NULL DEFAULT 'student',
  `IMAGE` varchar(50) NOT NULL,
  `CREATED_AT` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;